--Create table label
DROP TABLE IF EXISTS label;

CREATE TABLE label(
	id INT GENERATED BY DEFAULT AS IDENTITY,
	title VARCHAR(100) NOT NULL,
	color VARCHAR(100) NOT NULL,
	PRIMARY KEY(id)
);

--Create table genre
DROP TABLE IF EXISTS genre;

CREATE TABLE genre(
	id INT GENERATED BY DEFAULT AS IDENTITY,
	name VARCHAR(100) NOT NULL,
	PRIMARY KEY(id)
);

--Create table source
DROP TABLE IF EXISTS source;

CREATE TABLE source(
	id INT GENERATED BY DEFAULT AS IDENTITY,
	name VARCHAR(100) NOT NULL,
	PRIMARY KEY(id)
);

--Create table author
DROP TABLE IF EXISTS author;

CREATE TABLE author(
	id INT GENERATED BY DEFAULT AS IDENTITY,
	first_name VARCHAR(100) NOT NULL,
	last_name VARCHAR(100) NOT NULL,
	PRIMARY KEY(id)
);

--Create table book
DROP TABLE IF EXISTS book;

CREATE TABLE book(
	id INT GENERATED BY DEFAULT AS IDENTITY,
	genre_id INT,
	author_id INT,
	source_id INT,
	label_id INT,
	publish_date DATE NOT NULL,
	archived BOOLEAN,
	publisher VARCHAR(100) NOT NULL,
	cover_state VARCHAR(10) NOT NULL,
	PRIMARY KEY(id),
	CONSTRAINT fk_genre FOREIGN KEY(genre_id) REFERENCES genre(id),
	CONSTRAINT fk_author FOREIGN KEY(author_id) REFERENCES author(id),
	CONSTRAINT fk_source FOREIGN KEY(source_id) REFERENCES source(id),
	CONSTRAINT fk_label FOREIGN KEY(label_id) REFERENCES label(id)
);