
-- Create table game
Create Table Game (
    id serial PRIMARY KEY
    name VARCHAR(50),
    multiplayer BOOLEAN
    last_played_At DATE 
    publish_date DATE
    Archived BOOLEAN
    item_id INT FOREIGN KEY REFERENCES item(id)
)

--Create table author
Create Table author (
    id serial PRIMARY KEY
    first_name VARCHAR(50)
    last_name VARCHAR(50)
    item_id INT FOREIGN KEY REFERENCES item(id)
)

--Create music_albums table
create table music_albums(
  id serial not null primary key,
  archived boolean,
  publish_date date,
  on_spotify boolean
);

--Create genres table
create table genres(
  id serial not null primary key,
  name varchar(100)
);

--Create table label
DROP TABLE IF EXISTS label;

CREATE TABLE label(
	id INT GENERATED BY DEFAULT AS IDENTITY,
	title VARCHAR(100) NOT NULL,
	color VARCHAR(100) NOT NULL,
	PRIMARY KEY(id)
);

--Create table book
DROP TABLE IF EXISTS book;

CREATE TABLE book(
	id INT GENERATED BY DEFAULT AS IDENTITY,
	label_id INT,
	publish_date DATE NOT NULL,
	archived BOOLEAN,
	publisher VARCHAR(100) NOT NULL,
	cover_state VARCHAR(10) NOT NULL,
	PRIMARY KEY(id),
	CONSTRAINT fk_label FOREIGN KEY(label_id) REFERENCES label(id)
);

